web:
  static_path:
  port: 8080
  domain: 127.0.0.1:8080
  read_timeout: 5
  write_timeout: 5
  idle_timeout: 5
application:
    log:
        level: debug
        logPath: ./asset/log/log.log
gorm:
  debug: true
  db_type: mysql
  max_lifetime: 7200
  max_open_conns: 150
  max_idle_conns: 50
  mysql:
    host: rm-uf6r9070510k0qologo.mysql.rds.aliyuncs.com
    port: 3306
    user: pass_saas_cn_super
    password: K9dA3amSkZm7%##p
    db_name: globalization_language_document
    parameters: charset=utf8&parseTime=True&loc=Asia%2FShanghai
sqlite3:
  path: ./assets/database.sqlite